[package]
name = "ag"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "2.1.10"
clap = { version = "4.3.0", features = ["derive"] }
rand = "0.8.5"
csv = "1.2.1"
anyhow = "1.0.75"
ethers = { version = "2.0.14", features = ["rustls"] }
